var zones = 
[
	["1", "qeynos", "South Qeynos"],
	["2", "qeynos2", "North Qeynos"],
	["3", "qrg", "The Surefall Glade"],
	["4", "qeytoqrg", "The Qeynos Hills"],
	["5", "highpass", "Highpass Hold"],
	["6", "highkeep", "High Keep"],
	["8", "freportn", "North Freeport"],
	["9", "freportw", "West Freeport"],
	["10", "freporte", "East Freeport"],
	["11", "runnyeye", "The Liberated Citadel of Runnyeye"],
	["12", "qey2hh1", "The Western Plains of Karana"],
	["13", "northkarana", "The Northern Plains of Karana"],
	["14", "southkarana", "The Southern Plains of Karana"],
	["15", "eastkarana", "Eastern Plains of Karana"],
	["16", "beholder", "Gorge of King Xorbb"],
	["17", "blackburrow", "Blackburrow"],
	["18", "paw", "The Lair of the Splitpaw"],
	["19", "rivervale", "Rivervale"],
	["20", "kithicor", "Kithicor Forest"],
	["21", "commons", "West Commonlands"],
	["22", "ecommons", "East Commonlands"],
	["23", "erudnint", "The Erudin Palace"],
	["24", "erudnext", "Erudin"],
	["25", "nektulos", "The Nektulos Forest"],
	["25", "nektulos", "The Nektulos Forest"],
	["26", "cshome", "Sunset Home"],
	["27", "lavastorm", "The Lavastorm Mountains"],
	["28", "nektropos", "Nektropos"],
	["29", "halas", "Halas"],
	["30", "everfrost", "Everfrost Peaks"],
	["31", "soldunga", "Solusek's Eye"],
	["32", "soldungb", "Nagafen's Lair"],
	["33", "misty", "Misty Thicket"],
	["34", "nro", "Northern Desert of Ro"],
	["35", "sro", "Southern Desert of Ro"],
	["36", "befallen", "Befallen"],
	["37", "oasis", "Oasis of Marr"],
	["38", "tox", "Toxxulia Forest"],
	["39", "hole", "The Hole"],
	["40", "neriaka", "Neriak - Foreign Quarter"],
	["41", "neriakb", "Neriak - Commons"],
	["42", "neriakc", "Neriak - 3rd Gate"],
	["43", "neriakd", "Neriak Palace"],
	["44", "najena", "Najena"],
	["45", "qcat", "The Qeynos Aqueduct System"],
	["46", "innothule", "Innothule Swamp"],
	["47", "feerrott", "The Feerrott"],
	["48", "cazicthule", "Accursed Temple of CazicThule"],
	["49", "oggok", "Oggok"],
	["50", "rathemtn", "The Rathe Mountains"],
	["51", "lakerathe", "Lake Rathetear"],
	["52", "grobb", "Grobb"],
	["53", "aviak", "Aviak Village"],
	["54", "gfaydark", "The Greater Faydark"],
	["55", "akanon", "Ak'Anon"],
	["56", "steamfont", "Steamfont Mountains"],
	["57", "lfaydark", "The Lesser Faydark"],
	["58", "crushbone", "Crushbone"],
	["59", "mistmoore", "The Castle of Mistmoore"],
	["60", "kaladima", "South Kaladim"],
	["61", "felwithea", "Northern Felwithe"],
	["62", "felwitheb", "Southern Felwithe"],
	["63", "unrest", "The Estate of Unrest"],
	["64", "kedge", "Kedge Keep"],
	["65", "guktop", "The City of Guk"],
	["66", "gukbottom", "The Ruins of Old Guk"],
	["67", "kaladimb", "North Kaladim"],
	["68", "butcher", "Butcherblock Mountains"],
	["69", "oot", "Ocean of Tears"],
	["70", "cauldron", "Dagnor's Cauldron"],
	["71", "airplane", "The Plane of Sky"],
	["72", "fearplane", "The Plane of Fear"],
	["73", "permafrost", "The Permafrost Caverns"],
	["74", "kerraridge", "Kerra Isle"],
	["75", "paineel", "Paineel"],
	["76", "hateplane", "Plane of Hate"],
	["77", "arena", "The Arena"],
	["78", "fieldofbone", "The Field of Bone"],
	["79", "warslikswood", "The Warsliks Woods"],
	["80", "soltemple", "The Temple of Solusek Ro"],
	["81", "droga", "The Temple of Droga"],
	["82", "cabwest", "Cabilis West"],
	["83", "swampofnohope", "The Swamp of No Hope"],
	["84", "firiona", "Firiona Vie"],
	["85", "lakeofillomen", "Lake of Ill Omen"],
	["86", "dreadlands", "The Dreadlands"],
	["87", "burningwood", "The Burning Wood"],
	["88", "kaesora", "Kaesora"],
	["89", "sebilis", "The Ruins of Sebilis"],
	["90", "citymist", "The City of Mist"],
	["91", "skyfire", "The Skyfire Mountains"],
	["92", "frontiermtns", "Frontier Mountains"],
	["93", "overthere", "The Overthere"],
	["94", "emeraldjungle", "The Emerald Jungle"],
	["95", "trakanon", "Trakanon's Teeth"],
	["96", "timorous", "Timorous Deep"],
	["97", "kurn", "Kurn's Tower"],
	["98", "erudsxing", "Erud's Crossing"],
	["100", "stonebrunt", "The Stonebrunt Mountains"],
	["101", "warrens", "The Warrens"],
	["102", "karnor", "Karnor's Castle"],
	["103", "chardok", "Chardok"],
	["104", "dalnir", "The Crypt of Dalnir"],
	["105", "charasis", "The Howling Stones"],
	["106", "cabeast", "Cabilis East"],
	["107", "nurga", "The Mines of Nurga"],
	["108", "veeshan", "Veeshan's Peak"],
	["109", "veksar", "Veksar"],
	["110", "iceclad", "The Iceclad Ocean"],
	["111", "frozenshadow", "The Tower of Frozen Shadow"],
	["112", "velketor", "Velketor's Labyrinth"],
	["113", "kael", "Kael Drakkel"],
	["114", "skyshrine", "Skyshrine"],
	["115", "thurgadina", "The City of Thurgadin"],
	["116", "eastwastes", "Eastern Wastes"],
	["117", "cobaltscar", "Cobaltscar"],
	["118", "greatdivide", "The Great Divide"],
	["119", "wakening", "The Wakening Land"],
	["120", "westwastes", "The Western Wastes"],
	["121", "crystal", "The Crystal Caverns"],
	["123", "necropolis", "Dragon Necropolis"],
	["124", "templeveeshan", "The Temple of Veeshan"],
	["125", "sirens", "Siren's Grotto"],
	["126", "mischiefplane", "The Plane of Mischief"],
	["127", "growthplane", "The Plane of Growth"],
	["128", "sleeper", "The Sleeper's Tomb"],
	["129", "thurgadinb", "Icewell Keep"],
	["130", "erudsxing2", "Marauders Mire"],
	["150", "shadowhaven", "Shadow Haven"],
	["151", "bazaar", "The Bazaar"],
	["151", "bazaar", "The Bazaar"],
	["152", "nexus", "Nexus"],
	["153", "echo", "The Echo Caverns"],
	["154", "acrylia", "The Acrylia Caverns"],
	["155", "sharvahl", "The City of Shar Vahl"],
	["156", "paludal", "The Paludal Caverns"],
	["157", "fungusgrove", "The Fungus Grove"],
	["158", "vexthal", "Vex Thal"],
	["159", "sseru", "Sanctus Seru"],
	["160", "katta", "Katta Castellum"],
	["161", "netherbian", "Netherbian Lair"],
	["162", "ssratemple", "Ssraeshza Temple"],
	["163", "griegsend", "Grieg's End"],
	["164", "thedeep", "The Deep"],
	["165", "shadeweaver", "Shadeweaver's Thicket"],
	["166", "hollowshade", "Hollowshade Moor"],
	["167", "grimling", "Grimling Forest"],
	["168", "mseru", "Marus Seru"],
	["169", "letalis", "Mons Letalis"],
	["170", "twilight", "The Twilight Sea"],
	["171", "thegrey", "The Grey"],
	["172", "tenebrous", "The Tenebrous Mountains"],
	["173", "maiden", "The Maiden's Eye"],
	["174", "dawnshroud", "The Dawnshroud Peaks"],
	["175", "scarlet", "The Scarlet Desert"],
	["176", "umbral", "The Umbral Plains"],
	["179", "akheva", "The Akheva Ruins"],
	["180", "arena2", "The Arena Two"],
	["181", "jaggedpine", "The Jaggedpine Forest"],
	["182", "nedaria", "Nedaria's Landing"],
	["183", "tutorial", "EverQuest Tutorial"],
	["184", "load", "Loading Zone"],
	["185", "load2", "New Loading Zone"],
	["186", "hateplaneb", "The Plane of Hate"],
	["187", "shadowrest", "Shadowrest"],
	["188", "tutoriala", "The Mines of Gloomingdeep"],
	["189", "tutorialb", "The Mines of Gloomingdeep"],
	["190", "clz", "Loading"],
	["200", "codecay", "The Crypt of Decay"],
	["201", "pojustice", "The Plane of Justice"],
	["202", "poknowledge", "The Plane of Knowledge"],
	["203", "potranquility", "The Plane of Tranquility"],
	["204", "ponightmare", "The Plane of Nightmares"],
	["205", "podisease", "The Plane of Disease"],
	["206", "poinnovation", "The Plane of Innovation"],
	["207", "potorment", "Torment, the Plane of Pain"],
	["208", "povalor", "The Plane of Valor"],
	["209", "bothunder", "Bastion of Thunder"],
	["210", "postorms", "The Plane of Storms"],
	["211", "hohonora", "The Halls of Honor"],
	["212", "solrotower", "The Tower of Solusek Ro"],
	["213", "powar", "Plane of War"],
	["214", "potactics", "Drunder, the Fortress of Zek"],
	["215", "poair", "The Plane of Air"],
	["216", "powater", "The Plane of Water"],
	["217", "pofire", "The Plane of Fire"],
	["218", "poeartha", "The Plane of Earth"],
	["219", "potimea", "The Plane of Time"],
	["220", "hohonorb", "The Temple of Marr"],
	["221", "nightmareb", "The Lair of Terris Thule"],
	["222", "poearthb", "The Plane of Earth"],
	["223", "potimeb", "The Plane of Time"],
	["224", "gunthak", "The Gulf of Gunthak"],
	["225", "dulak", "Dulak's Harbor"],
	["226", "torgiran", "The Torgiran Mines"],
	["227", "nadox", "The Crypt of Nadox"],
	["228", "hatesfury", "Hate's Fury"],
	["229", "guka", "Deepest Guk: Cauldron of Lost Souls"],
	["230", "ruja", "The Rujarkian Hills: Bloodied Quarries"],
	["231", "taka", "Takish-Hiz: Sunken Library"],
	["232", "mira", "Miragul's Menagerie: Silent Gallery"],
	["233", "mmca", "Mistmoore's Catacombs: Forlorn Caverns"],
	["234", "gukb", "The Drowning Crypt"],
	["235", "rujb", "The Rujarkian Hills: Halls of War"],
	["236", "takb", "Takish-Hiz: Shifting Tower"],
	["237", "mirb", "Miragul's Menagerie: Frozen Nightmare"],
	["238", "mmcb", "Mistmoore's Catacombs: Dreary Grotto"],
	["239", "gukc", "Deepest Guk: Ancient Aqueducts"],
	["240", "rujc", "The Rujarkian Hills: Wind Bridges"],
	["241", "takc", "Takish-Hiz: Within the Compact"],
	["242", "mirc", "The Spider Den"],
	["243", "mmcc", "Mistmoore's Catacombs: Struggles within the Progeny"],
	["244", "gukd", "The Mushroom Grove"],
	["245", "rujd", "The Rujarkian Hills: Prison Break"],
	["246", "takd", "Takish-Hiz: Royal Observatory"],
	["247", "mird", "Miragul's Menagerie: Hushed Banquet"],
	["248", "mmcd", "Mistmoore's Catacombs: Chambers of Eternal Affliction"],
	["249", "guke", "Deepest Guk: The Curse Reborn"],
	["250", "ruje", "The Rujarkian Hills: Drudge Hollows"],
	["251", "take", "Takish-Hiz: River of Recollection"],
	["252", "mire", "The Frosted Halls"],
	["253", "mmce", "Mistmoore's Catacombs: Sepulcher of the Damned"],
	["254", "gukf", "Deepest Guk: Chapel of the Witnesses"],
	["255", "rujf", "The Rujarkian Hills: Fortified Lair of the Taskmasters"],
	["256", "takf", "Takish-Hiz: Sandfall Corridors"],
	["257", "mirf", "The Forgotten Wastes"],
	["258", "mmcf", "Mistmoore's Catacombs: Scion Lair of Fury"],
	["259", "gukg", "The Root Garden"],
	["260", "rujg", "The Rujarkian Hills: Hidden Vale of Deceit"],
	["261", "takg", "Takish-Hiz: Balancing Chamber"],
	["262", "mirg", "Miragul's Menagerie: Heart of the Menagerie"],
	["263", "mmcg", "Mistmoore's Catacombs: Cesspits of Putrescence"],
	["264", "gukh", "Deepest Guk: Accursed Sanctuary"],
	["265", "rujh", "The Rujarkian Hills: Blazing Forge "],
	["266", "takh", "Takish-Hiz: Sweeping Tides"],
	["267", "mirh", "The Morbid Laboratory"],
	["268", "mmch", "Mistmoore's Catacombs: Aisles of Blood"],
	["269", "ruji", "The Rujarkian Hills: Arena of Chance"],
	["270", "taki", "Takish-Hiz: Antiquated Palace"],
	["271", "miri", "The Theater of Imprisoned Horror"],
	["272", "mmci", "Mistmoore's Catacombs: Halls of Sanguinary Rites"],
	["273", "rujj", "The Rujarkian Hills: Barracks of War"],
	["274", "takj", "Takish-Hiz: Prismatic Corridors"],
	["275", "mirj", "Miragul's Menagerie: Grand Library"],
	["276", "mmcj", "Mistmoore's Catacombs: Infernal Sanctuary"],
	["277", "chardokb", "Chardok: The Halls of Betrayal"],
	["278", "soldungc", "The Caverns of Exile"],
	["279", "abysmal", "The Abysmal Sea"],
	["280", "natimbi", "Natimbi, the Broken Shores"],
	["281", "qinimi", "Qinimi, Court of Nihilia"],
	["282", "riwwi", "Riwwi, Coliseum of Games"],
	["283", "barindu", "Barindu, Hanging Gardens"],
	["284", "ferubi", "Ferubi, Forgotten Temple of Taelosia"],
	["285", "snpool", "Sewers of Nihilia, Pool of Sludg"],
	["286", "snlair", "Sewers of Nihilia, Lair of Trapp"],
	["287", "snplant", "Sewers of Nihilia, Purifying Pla"],
	["288", "sncrematory", "Sewers of Nihilia, Emanating Cre"],
	["289", "tipt", "Tipt, Treacherous Crags"],
	["290", "vxed", "Vxed, the Crumbling Caverns"],
	["291", "yxtta", "Yxtta, Pulpit of Exiles "],
	["292", "uqua", "Uqua, the Ocean God Chantry"],
	["293", "kodtaz", "Kod'Taz, Broken Trial Grounds"],
	["294", "ikkinz", "Ikkinz, Chambers of Transcendence"],
	["295", "qvic", "Qvic, Prayer Grounds of Calling"],
	["296", "inktuta", "Inktu'Ta, the Unmasked Chapel"],
	["297", "txevu", "Txevu, Lair of the Elite"],
	["298", "tacvi", "Tacvi, The Broken Temple"],
	["299", "qvicb", "Qvic, the Hidden Vault"],
	["300", "wallofslaughter", "Wall of Slaughter"],
	["301", "bloodfields", "The Bloodfields"],
	["302", "draniksscar", "Dranik's Scar"],
	["303", "causeway", "Nobles' Causeway"],
	["304", "chambersa", "Muramite Proving Grounds"],
	["305", "chambersb", "Muramite Proving Grounds"],
	["306", "chambersc", "Muramite Proving Grounds"],
	["307", "chambersd", "Muramite Proving Grounds"],
	["308", "chamberse", "Muramite Proving Grounds"],
	["309", "chambersf", "Muramite Proving Grounds"],
	["316", "provinggrounds", "Muramite Proving Grounds"],
	["317", "anguish", "Anguish, the Fallen Palace"],
	["318", "dranikhollowsa", "Dranik's Hollows"],
	["319", "dranikhollowsb", "Dranik's Hollows"],
	["320", "dranikhollowsc", "Dranik's Hollows"],
	["328", "dranikcatacombsa", "Catacombs of Dranik"],
	["329", "dranikcatacombsb", "Catacombs of Dranik"],
	["330", "dranikcatacombsc", "Catacombs of Dranik"],
	["331", "draniksewersa", "Sewers of Dranik"],
	["332", "draniksewersb", "Sewers of Dranik"],
	["333", "draniksewersc", "Sewers of Dranik"],
	["334", "riftseekers", "Riftseekers' Sanctum"],
	["335", "harbingers", "Harbinger's Spire"],
	["336", "dranik", "The Ruined City of Dranik"],
	["337", "broodlands", "The Broodlands"],
	["338", "stillmoona", "Stillmoon Temple"],
	["339", "stillmoonb", "The Ascent"],
	["340", "thundercrest", "Thundercrest Isles"],
	["341", "delvea", "Lavaspinner's Lair"],
	["342", "delveb", "Tirranun's Delve"],
	["343", "thenest", "The Nest"],
	["344", "guildlobby", "Guild Lobby"],
	["345", "guildhall", "Guild Hall"],
	["346", "barter", "The Barter Hall"],
	["347", "illsalin", "Ruins of Illsalin"],
	["348", "illsalina", "Illsalin Marketplace"],
	["349", "illsalinb", "Temple of Korlach"],
	["350", "illsalinc", "The Nargil Pits"],
	["351", "dreadspire", "Dreadspire Keep"],
	["354", "drachnidhive", "The Hive"],
	["355", "drachnidhivea", "The Hatchery"],
	["356", "drachnidhiveb", "The Cocoons"],
	["357", "drachnidhivec", "Queen Sendaii`s Lair"],
	["358", "westkorlach", "Stoneroot Falls"],
	["359", "westkorlacha", "Prince's Manor"],
	["360", "westkorlachb", "Caverns of the Lost"],
	["361", "westkorlachc", "Lair of the Korlach"],
	["362", "eastkorlach", "The Undershore"],
	["363", "eastkorlacha", "Snarlstone Dens"],
	["364", "shadowspine", "Shadow Spine"],
	["365", "corathus", "Corathus Creep"],
	["366", "corathusa", "Sporali Caverns"],
	["367", "corathusb", "The Corathus Mines"],
	["368", "nektulosa", "Shadowed Grove"],
	["369", "arcstone", "Arcstone, Isle of Spirits"],
	["370", "relic", "Relic, the Artifact City"],
	["371", "skylance", "Skylance"],
	["372", "devastation", "The Devastation"],
	["373", "devastationa", "The Seething Wall"],
	["374", "rage", "Sverag, Stronghold of Rage"],
	["375", "ragea", "Razorthorn, Tower of Sullon Zek"],
	["376", "takishruins", "Ruins of Takish-Hiz"],
	["377", "takishruinsa", "The Root of Ro"],
	["378", "elddar", "The Elddar Forest"],
	["379", "elddara", "Tunare's Shrine"],
	["380", "theater", "Theater of Blood"],
	["381", "theatera", "Deathknell, Tower of Dissonance"],
	["382", "freeporteast", "East Freeport"],
	["383", "freeportwest", "West Freeport"],
	["384", "freeportsewers", "Freeport Sewers"],
	["385", "freeportacademy", "Academy of Arcane Sciences"],
	["386", "freeporttemple", "Temple of Marr"],
	["387", "freeportmilitia", "Freeport Militia House: My Precious"],
	["388", "freeportarena", "Arena"],
	["389", "freeportcityhall", "City Hall"],
	["390", "freeporttheater", "Theater of the Tranquil"],
	["391", "freeporthall", "Hall of Truth: Bounty"],
	["392", "northro", "North Desert of Ro"],
	["393", "southro", "South Desert of Ro"],
	["394", "crescent", "Crescent Reach"],
	["395", "moors", "Blightfire Moors"],
	["396", "stonehive", "Stone Hive"],
	["397", "mesa", "Goru`kar Mesa"],
	["398", "roost", "Blackfeather Roost"],
	["399", "steppes", "The Steppes"],
	["400", "icefall", "Icefall Glacier"],
	["401", "valdeholm", "Valdeholm"],
	["402", "frostcrypt", "Frostcrypt, Throne of the Shade King"],
	["403", "sunderock", "Sunderock Springs"],
	["404", "vergalid", "Vergalid Mines"],
	["405", "direwind", "Direwind Cliffs"],
	["406", "ashengate", "Ashengate, Reliquary of the Scale"],
	["407", "highpasshold", "Highpass Hold"],
	["408", "commonlands", "The Commonlands"],
	["409", "oceanoftears", "The Ocean of Tears"],
	["410", "kithforest", "Kithicor Forest"],
	["411", "befallenb", "Befallen"],
	["412", "highpasskeep", "HighKeep"],
	["413", "innothuleb", "The Innothule Swamp"],
	["414", "toxxulia", "Toxxulia Forest"],
	["415", "mistythicket", "The Misty Thicket"],
	["416", "kattacastrum", "Katta Castrum"],
	["417", "thalassius", "Thalassius, the Coral Keep"],
	["418", "atiiki", "Jewel of Atiiki"],
	["419", "zhisza", "Zhisza, the Shissar Sanctuary"],
	["420", "silyssar", "Silyssar, New Chelsith"],
	["421", "solteris", "Solteris, the Throne of Ro"],
	["422", "barren", "Barren Coast"],
	["423", "buriedsea", "The Buried Sea"],
	["424", "jardelshook", "Jardel's Hook"],
	["425", "monkeyrock", "Monkey Rock"],
	["426", "suncrest", "Suncrest Isle"],
	["427", "deadbone", "Deadbone Reef"],
	["428", "blacksail", "Blacksail Folly"],
	["429", "maidensgrave", "Maiden's Grave"],
	["430", "redfeather", "Redfeather Isle"],
	["431", "shipmvp", "The Open Sea"],
	["432", "shipmvu", "The Open Sea"],
	["433", "shippvu", "The Open Sea"],
	["434", "shipuvu", "The Open Sea"],
	["435", "shipmvm", "The Open Sea"],
	["436", "mechanotus", "Fortress Mechanotus"],
	["437", "mansion", "Meldrath's Majestic Mansion"],
	["438", "steamfactory", "The Steam Factory"],
	["439", "shipworkshop", "S.H.I.P. Workshop"],
	["440", "gyrospireb", "Gyrospire Beza"],
	["441", "gyrospirez", "Gyrospire Zeka"],
	["442", "dragonscale", "Dragonscale Hills"],
	["443", "lopingplains", "Loping Plains"],
	["444", "hillsofshade", "Hills of Shade"],
	["445", "bloodmoon", "Bloodmoon Keep"],
	["446", "crystallos", "Crystallos, Lair of the Awakened"],
	["447", "guardian", "The Mechamatic Guardian"],
	["448", "steamfontmts", "The Steamfont Mountains"],
	["449", "cryptofshade", "Crypt of Shade"],
	["451", "dragonscaleb", "Deepscar's Den"],
	["452", "oldfieldofbone", "Field of Scale"],
	["453", "oldkaesoraa", "Kaesora Library"],
	["454", "oldkaesorab", "Kaesora Hatchery"],
	["455", "oldkurn", "Kurn's Tower"],
	["456", "oldkithicor", "Bloody Kithicor"],
	["457", "oldcommons", "Old Commonlands"],
	["458", "oldhighpass", "Highpass Hold"],
	["459", "thevoida", "The Void"],
	["460", "thevoidb", "The Void"],
	["461", "thevoidc", "The Void"],
	["462", "thevoidd", "The Void"],
	["463", "thevoide", "The Void"],
	["464", "thevoidf", "The Void"],
	["465", "thevoidg", "The Void"],
	["466", "oceangreenhills", "Oceangreen Hills"],
	["467", "oceangreenvillage", "Oceangreen Village"],
	["468", "oldblackburrow", "BlackBurrow"],
	["469", "bertoxtemple", "Temple of Bertoxxulous"],
	["470", "discord", "Korafax, Home of the Riders"],
	["471", "discordtower", "Citadel of the Worldslayer"],
	["472", "oldbloodfield", "Old Bloodfields"],
	["473", "precipiceofwar", "The Precipice of War"],
	["474", "olddranik", "City of Dranik"],
	["475", "toskirakk", "Toskirakk"],
	["476", "korascian", "Korascian Warrens"],
	["477", "rathechamber", "Rathe Council Chamber"],
	["480", "brellsrest", "Brell's Rest"],
	["481", "fungalforest", "Fungal Forest"],
	["482", "underquarry", "The Underquarry"],
	["483", "coolingchamber", "The Cooling Chamber"],
	["484", "shiningcity", "Kernagir, the Shining City"],
	["485", "arthicrex", "Arthicrex"],
	["486", "foundation", "The Foundation"],
	["487", "lichencreep", "Lichen Creep"],
	["488", "pellucid", "Pellucid Grotto"],
	["489", "stonesnake", "Volska's Husk"],
	["490", "brellstemple", "Brell's Temple"],
	["491", "convorteum", "The Convorteum"],
	["492", "brellsarena", "Brell's Arena"],
	["493", "weddingchapel", "Wedding Chapel"],
	["494", "weddingchapeldark", "Wedding Chapel"],
	["495", "dragoncrypt", "Lair of the Risen"],
	["700", "feerrott2", "The Feerrott"],
	["701", "thulehouse1", "House of Thule"],
	["702", "thulehouse2", "House of Thule, Upper Floors"],
	["703", "housegarden", "The Grounds"],
	["704", "thulelibrary", "The Library"],
	["705", "well", "The Well"],
	["706", "fallen", "Erudin Burning"],
	["707", "morellcastle", "Morell's Castle"],
	["708", "somnium", "Sanctum Somnium"],
	["709", "alkabormare", "Al'Kabor's Nightmare"],
	["710", "miragulmare", "Miragul's Nightmare"],
	["711", "thuledream", "Fear Itself"],
	["712", "neighborhood", "Sunrise Hills"],
	["724", "argath", "Argath, Bastion of Illdaera"],
	["725", "arelis", "Valley of Lunanyn"],
	["726", "sarithcity", "Sarith, City of Tides"],
	["727", "rubak", "Rubak Oseka, Temple of the Sea"],
	["728", "beastdomain", "Beasts' Domain"],
	["729", "resplendent", "The Resplendent Temple"],
	["730", "pillarsalra", "Pillars of Alra"],
	["731", "windsong", "Windsong Sanctuary"],
	["732", "cityofbronze", "Erillion, City of Bronze"],
	["733", "sepulcher", "Sepulcher of Order"],
	["734", "eastsepulcher", "Sepulcher East"],
	["735", "westsepulcher", "Sepulcher West"],
	["752", "shardslanding", "Shard's Landing"],
	["753", "xorbb", "Valley of King Xorbb"],
	["754", "kaelshard", "Kael Drakkel: The King's Madness"],
	["755", "eastwastesshard", "East Wastes: Zeixshi-Kar's Awakening"],
	["756", "crystalshard", "The Crystal Caverns: Fragment of Fear"],
	["757", "breedinggrounds", "The Breeding Grounds"],
	["758", "eviltree", "Evantil, the Vile Oak"],
	["759", "grelleth", "Grelleth's Palace, the Chateau of Filth"],
	["760", "chapterhouse", "Chapterhouse of the Fallen"],
	["996", "arttest", "Art Testing Domain"],
	["998", "fhalls", "The Forgotten Halls"],
	["999", "apprentice", "Designer Apprentice"]
]